### ISSUE TITLE
Cacti 1.2.22 - RRDfile is not created / updated, possibly due to Spine bug

### ISSUE THREAD

**Issue by janmaris** [Cacti/spine#285]
Hi, the cactid service is running fine, but the RRD files are not created or updated, possibly due to a Segmentation Violation issue with Spine (currently using version 1.2.23).

debugging output is as follows:

```
root@server:/usr/local/spine/bin# gdb spine
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from spine...
(gdb) run -R -C /usr/local/spine/etc/spine.conf.dist
Starting program: /usr/local/spine/bin/spine -R -C /usr/local/spine/etc/spine.conf.dist
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
SPINE: Using spine config file [/usr/local/spine/etc/spine.conf.dist]

Program received signal SIGSEGV, Segmentation fault.
0x000055568946f030 in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1255
1255            va_start(args, format);
(gdb) where
#0  0x000055568946f030 in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1255
Cacti/cacti#1  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
Cacti/cacti#2  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
Cacti/cacti#3  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
Cacti/cacti#4  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
Cacti/cacti#5  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
Cacti/cacti#6  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
Cacti/cacti#7  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
Cacti/cacti#8  0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
Cacti/cacti#9  0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
Cacti/cacti#10 0x000055568946f34a in spine_log (format=format@entry=0x555689483800 "LOCKS: [START] Mutex lock for %s") at util.c:1316
Cacti/cacti#11 0x0000555689474f76 in thread_mutex_lock (mutex=mutex@entry=5) at locks.c:235
Cacti/cacti#12 0x000055568946f34a in spine_log (format=format@entry=0x55568947f81b "DEVDBG: SQL:%s") at util.c:1316
Cacti/cacti#13 0x000055568946d988 in db_query (mysql=mysql@entry=0x7ffdad89d030, type=type@entry=0, query=query@entry=0x7ffdad89c8e0 "SELECT value FROM settings WHERE name = 'path_webroot'") at sql.c:156
Cacti/cacti#14 0x000055568946e854 in getsetting (psql=psql@entry=0x7ffdad89d030, setting=setting@entry=0x5556894826e7 "path_webroot", mode=0) at util.c:100
Cacti/cacti#15 0x0000555689471919 in read_config_options () at util.c:385
Cacti/cacti#16 0x000055568946bf88 in main (argc=<optimized out>, argv=<optimized out>) at spine.c:492
(gdb) list
1250            char flogmessage[LOGSIZE];     /* Formatted Log Message */
1251            char stdoutmessage[LRG_LOGSIZE];   /* Message for stdout */
1252
1253            double cur_time;
1254
1255            va_start(args, format);
1256            vsnprintf(ulogmessage, LOGSIZE - 1, format, args);
1257            va_end(args);
1258
1259            /* default for "console" messages to go to stdout */
(gdb)
```

Thanks for any further help or suggestions to get this resolved.
Jan

**Comment by janmaris** [comment]
Hi ,
I'm sure I'm running spine 1.2.23, as you can see from the output below:

```
root@server:/usr/local/spine/bin# ./spine -h
SPINE 1.2.23  Copyright 2004-2021 by The Cacti Group

Usage: spine [options] [[firstid lastid] || [-H/--hostlist='hostid1,hostid2,...,hostidn']]

Options:
  -h/--help          Show this brief help listing
  -f/--first=X       Start polling with host id X
  -l/--last=X        End polling with host id X
  -H/--hostlist=X    Poll the list of host ids, separated by comma's
  -p/--poller=X      Set the poller id to X
  -C/--conf=F        Read spine configuration from file F
  -O/--option=S:V    Override DB settings 'set' with value 'V'
  -M/--mibs          Refresh the device System Mib data
  -N/--mode=online   For remote pollers, the operating mode.
                     Options include: online, offline, recovery.
                     The default is 'online'.
  -R/--readonly      Spine will not write output to the DB
  -S/--stdout        Logging is performed to standard output
  -V/--verbosity=V   Set logging verbosity to <V>

Either both of --first/--last must be provided, a valid hostlist must be provided.
In their absence, all hosts are processed.

Without the --conf parameter, spine searches for its spine.conf
file in the usual places.

Verbosity is one of NONE/LOW/MEDIUM/HIGH/DEBUG or 1..5

Runtime options are read from the 'settings' table in the Cacti
database, but they can be overridden with the --option=S:V
parameter.

Spine is distributed under the Terms of the GNU Lesser
General Public License Version 2.1. (http://www.gnu.org/licenses/lgpl.txt)
For more information, see http://www.cacti.net

```


If you still believe I'm running the developer branch: how would I be able to verify this?

**Comment by janmaris** [comment]
And is it actually OK to use Cacti 1.2.22 with Spine 1.2.23 ?

**Comment by janmaris** [comment]
Answering your question regarding the OS and version:

I'm running Debian 11 Bullseye - version 11.5
`Linux server 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux`
 all packages up to date.

**Comment by TheWitness** [comment]
The answer is mostly yes.  If no, we would change either minor or point releases.  For example, you cannot use spine 1.1 with cacti 1.2 and vice versa.  But any 1.2.x will generally work with one another.

**Comment by TheWitness** [comment]
Take another snapshot of 1.2.x branch.  @netniV made some changes recently.  I've got no issues running the latest spine on either RHEL7.9 or RHEL8.5.

**Comment by TheWitness** [comment]
No feedback.
