### ISSUE TITLE
SIGSEGV, Segmentation fault after upgrade 1.2.7 to  1.2.23 

### ISSUE THREAD

**Issue by djpa3k** [Cacti/spine#296]
Hi,

when i upgrade from 1.2.7 to 1.2.23 i get SIGSEGV when is not posible get device uptime from OID .1.3.6.1.2.1.1.3.0 

```
(gdb) run -V 5 -R -C /usr/local/spine/etc/spine.conf
Starting program: /root/cacti-spine-1.2.23/./spine -V 5 -R -C /usr/local/spine/etc/spine.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
SPINE: Using spine config file [/usr/local/spine/etc/spine.conf]
[New Thread 0x7ffff48ba700 (LWP 28428)]
[Thread 0x7ffff48ba700 (LWP 28428) exited]
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The path_php_server variable is /var/www/script_server.php
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The path_cactilog variable is /var/www/log/cacti.log
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The version variable is 5.5.68-MariaDB
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The log_destination variable is 1 (FILE)
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The path_php variable is /usr/bin/php
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The availability_method variable is 1
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The ping_recovery_count variable is 2
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The ping_failure_count variable is 2
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The ping_method variable is 2
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The ping_retries variable is 3
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The ping_timeout variable is 900
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The snmp_retries variable is 3
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The log_perror variable is 1
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The log_pwarn variable is 0
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The boost_redirect variable is 0
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The boost_rrd_update_enable variable is 0
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The log_pstats variable is 0
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The threads variable is 1
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The polling interval is 300 seconds
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The number of concurrent processes is 6
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The script timeout is 35
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The selective_device_debug variable is
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The spine_log_level variable is 0
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The number of php script servers to run is 2
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The number of active data source profiles is 2
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The number of snmp ports on the system is 3
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: StartDevice='-1', EndDevice='-1', TotalPHPScripts='1'
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The PHP Script Server is Required
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: The Maximum SNMP OID Get Size is 30
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Total Connections made 1
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Creating Local Connection Pool of 1 threads.
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Creating Local Connection 0.
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Total Connections made 2
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Version 1.2.23 starting
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: MySQL is Thread Safe!
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Spine running as 0 UID, 0 EUID
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Spine is running as root.
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Spine has got ICMP
2023/01/09 10:18:30 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Initializing Net-SNMP API
.......
.......
.......
[New Thread 0x7ffff48ba700 (LWP 28438)]
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Valid Thread to be Created (140737296180992)
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] DEBUG: Device[147] HT[1] In Poller, About to Start Polling
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737354020992] DEBUG: Available Threads is 0 (1 outstanding)
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] DEBUG: Traversing Local Connection Pool for free connection.
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] DEBUG: Checking Local Pool ID 0.
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] DEBUG: Allocating Local Pool ID 0.
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] get_namebyhost(10.99.0.250) - Allocating name_t
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] get_namebyhost(10.99.0.250) - No delimiter, assume full hostname
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] Device[147] INFO: SNMP Device '10.99.0.250:161' has a timeout of 700000 (700), with 3 retries
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] Device[147] IPv4 address 10.99.0.250 (10.99.0.250)
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] Device[147] DEBUG: Entering ICMP Ping
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] Device[147] DEBUG: Attempting to ping 10.99.0.250, seq 0 (Retry 0 of 3)
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] Device[147] DEBUG: ICMP Device Alive, Try Count:1, Time:0.8750 ms
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] Device[147] PING: Result ICMP: Device is Alive
2023/01/09 10:18:31 - SPINE: Poller[1] PID[28424] PT[140737296180992] DEBUG: Device[147] HT[1] RECACHE: Processing 2 items in the auto reindex cache for '10.99.0.250'
2023/01/09 10:18:34 - SPINE: Poller[1] PID[28424] PT[140737296180992] ERROR: Timeout getting oid '.1.3.6.1.2.1.1.3.0' for Device[147] with Status[2]
2023/01/09 10:18:34 - SPINE: Poller[1] PID[28424] PT[140737296180992] Device[147] HT[1] DQ[1] Legacy Uptime Result: U, Is Numeric: 0
2023/01/09 10:18:34 - SPINE: Poller[1] PID[28424] PT[140737296180992] WARNING: Skipped oid '.1.3.6.1.6.3.10.2.1.3.0' for Device[147] as host ignore flag is active

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff48ba700 (LWP 28438)]
0x00007ffff6275162 in vsnprintf () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-55.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 mariadb-libs-5.5.68-1.el7.x86_64 net-snmp-libs-5.7.2-49.el7_9.2.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
```
```
(gdb) bt
#0  0x00007ffff6275162 in vsnprintf () from /lib64/libc.so.6
#1  0x00007ffff6250582 in snprintf () from /lib64/libc.so.6
#2  0x00000000004106b4 in poll_host (device_counter=1, host_id=147, host_thread=1, host_threads=1, host_data_ids=<optimized out>, host_time=0x7ffff48b9cb0 "1673255911", host_errors=0x7ffff48b9bdc,
    host_time_double=1673255911.45294) at poller.c:910
#3  0x00000000004117fe in child (arg=0x6e5460) at poller.c:109
#4  0x00007ffff6844ea5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007ffff62fbb0d in clone () from /lib64/libc.so.6
```
**Server**
 CentOS Linux release 7.9.2009 (Core)
 Linux cacti 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Compiling:**

autoconf: 2.69
glibc: 2.17
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
source: https://files.cacti.net/spine/cacti-spine-1.2.23.tar.gz

**Comment by netniV** [comment]
I recall fixing an issue with that OID.... but I haven't had any segmentation issues.  Trying to recall if that was in 1.2.x or 1.3.x

**Comment by TheWitness** [comment]
@djpa3k, thanks for reporting this.  Continue to use the old version for now.

**Comment by TheWitness** [comment]
@netniV you did make a change in 1.2.x to correct another issue.  This may be an unintended consequence of the change though.

**Comment by djpa3k** [comment]
this bug starts from 3114ac83c6c55a51b9d33af94795eefcbcc4f8e2 
Before this commit process exited normally.
I know, it's also related to my old distro

Thnx

**Comment by netniV** [comment]
Agreed.  Change looks good, just need a CHANGELOG entry 👍

**Comment by netniV** [comment]
Thanks for the report and the pull request fix.  This has now been applied to both the 1.2.x and 1.3.x (develop) branches.
